pub enum Instruction {
    ISLT { a: u8, d: u16 },
    ISGE { a: u8, d: u16 },
    ISLE { a: u8, d: u16 },
    ISGT { a: u8, d: u16 },
    ISEQV { a: u8, d: u16 },
    ISNEV { a: u8, d: u16 },
    ISEQS { a: u8, d: u16 },
    ISNES { a: u8, d: u16 },
    ISEQN { a: u8, d: u16 },
    ISNEN { a: u8, d: u16 },
    ISEQP { a: u8, d: u16 },
    ISNEP { a: u8, d: u16 },

    ISTC { a: u8, d: u16 },
    ISFC { a: u8, d: u16 },
    IST { d: u16 },
    ISF { d: u16 },

    MOV { a: u8, d: u16 },
    NOT { a: u8, d: u16 },
    UNM { a: u8, d: u16 },
    LEN { a: u8, d: u16 },

    ADDVN { a: u8, b: u8, c: u8 },
    SUBVN { a: u8, b: u8, c: u8 },
    MULVN { a: u8, b: u8, c: u8 },
    DIVVN { a: u8, b: u8, c: u8 },
    MODVN { a: u8, b: u8, c: u8 },
    ADDNV { a: u8, b: u8, c: u8 },
    SUBNV { a: u8, b: u8, c: u8 },
    MULNV { a: u8, b: u8, c: u8 },
    DIVNV { a: u8, b: u8, c: u8 },
    MODNV { a: u8, b: u8, c: u8 },
    ADDVV { a: u8, b: u8, c: u8 },
    SUBVV { a: u8, b: u8, c: u8 },
    MULVV { a: u8, b: u8, c: u8 },
    DIVVV { a: u8, b: u8, c: u8 },
    MODVV { a: u8, b: u8, c: u8 },
    POW { a: u8, b: u8, c: u8 },
    CAT { a: u8, b: u8, c: u8 },

    KSTR { a: u8, d: u16 },
    KCDATA { a: u8, d: u16 },
    KSHORT { a: u8, d: u16 },
    KNUM { a: u8, d: u16 },
    KPRI { a: u8, d: u16 },
    KNIL { a: u8, d: u16 },

    UGET { a: u8, d: u16 },
    USETV { a: u8, d: u16 },
    USETS { a: u8, d: u16 },
    USETN { a: u8, d: u16 },
    USETP { a: u8, d: u16 },
    UCLO { a: u8, d: u16 },
    FNEW { a: u8, d: u16 },

    TNEW { a: u8, d: u16 },
    TDUP { a: u8, d: u16 },
    GGET { a: u8, d: u16 },
    GSET { a: u8, d: u16 },
    TGETV { a: u8, b: u8, c: u8 },
    TGETS { a: u8, b: u8, c: u8 },
    TGETB { a: u8, b: u8, c: u8 },
    TSETV { a: u8, b: u8, c: u8 },
    TSETS { a: u8, b: u8, c: u8 },
    TSETB { a: u8, b: u8, c: u8 },
    TSETM { a: u8, d: u16 },

    CALLM { a: u8, b: u8, c: u8 },
    CALL { a: u8, b: u8, c: u8 },
    CALLMT { a: u8, d: u16 },
    CALLT { a: u8, d: u16 },
    ITERC { a: u8, b: u8, c: u8 },
    ITERN { a: u8, b: u8, c: u8 },
    VARG { a: u8, b: u8, c: u8 },
    ISNEXT { a: u8, d: u16 },

    RETM { a: u8, d: u16 },
    RET { a: u8, d: u16 },
    RET0 { a: u8, d: u16 },
    RET1 { a: u8, d: u16 },

    FORI { a: u8, d: u16 },
    JFORI { a: u8, d: u16 },
    FORL { a: u8, d: u16 },
    IFORL { a: u8, d: u16 },
    ITERL { a: u8, d: u16 },
    IITERL { a: u8, d: u16 },
    JITERL { a: u8, d: u16 },
    LOOP { a: u8, d: u16 },
    ILOOP { a: u8, d: u16 },
    JLOOP { a: u8, d: u16 },
    JMP { a: u8, d: u16 },

    FUNCF { a: u8 },
    IFUNCF { a: u8 },
    JFUNCF { a: u8, d: u16 },
    FUNCV { a: u8 },
    IFUNCV { a: u8 },
    JFUNCV { a: u8, d: u16 },
    FUNCC { a: u8 },
    FUNCCW { a: u8 },
    FUNC { a: u8 },
}
